field_validation.rule_set.*:
  type: config_entity
  label: 'Field validation rule set'
  mapping:
    name:
      type: string
      label: 'Name'
    label:
      type: string
      label: 'Label'
    entity_type:
      type: string
      label: 'Entity type'
    bundle:
      type: string
      label: 'Entity bundle'
    field_validation_rules:
      type: sequence
      sequence:
        type: mapping
        mapping:
          id:
            type: string
            label: 'ID'
          title:
            type: label
            label: 'Rule name'
          data:
            type: field_validation.rule.[%parent.id]
            label: 'Data'
          weight:
            type: integer
            label: 'Weight'
          uuid:
            type: string
            label: 'UUID'
          field_name:
            type: string
            label: 'Field name'
          column:
            type: string
            label: 'Field column'
          error_message:
            type: string
            label: 'Error message'
          roles:
            type: sequence
            sequence:
              type: string
          condition:
            type: mapping
            mapping:
              field:
                type: string
                label: 'Field name'
              operator:
                type: string
                label: 'Operator'
              value:
                type: string
                label: 'Value'

field_validation.rule.*:
  type: mapping
  label: 'Field validation rule'

field_validation.rule.length_constraint_rule:
  type: mapping
  label: 'Length constraint validation rule'
  mapping:
    validate_mode:
      type: string
      label: 'Validate mode'
    min:
      type: string
      label: 'Min'
    max:
      type: string
      label: 'Max'
    maxMessage:
      type: string
      label: 'Max message'
    minMessage:
      type: string
      label: 'Min message'
    exactMessage:
      type: string
      label: 'Exact message'

field_validation.rule.regex_constraint_rule:
  type: mapping
  label: 'Regex constraint validation rule'
  mapping:
    validate_mode:
      type: string
      label: 'Validate mode'
    pattern:
      type: string
      label: 'Pattern'
    message:
      type: string
      label: 'Message'

field_validation.rule.email_constraint_rule:
  type: mapping
  label: 'Email constraint validation rule'
  mapping:
    validate_mode:
      type: string
      label: 'Validate mode'
    message:
      type: string
      label: 'Message'

field_validation.rule.null_constraint_rule:
  type: mapping
  label: 'IsNull constraint validation rule'
  mapping:
    validate_mode:
      type: string
      label: 'Validate mode'
    message:
      type: string
      label: 'Message'

field_validation.rule.not_null_constraint_rule:
  type: mapping
  label: 'NotNull constraint validation rule'
  mapping:
    validate_mode:
      type: string
      label: 'Validate mode'
    message:
      type: string
      label: 'Message'

field_validation.rule.unique_field_constraint_rule:
  type: mapping
  label: 'Unique field constraint validation rule'
  mapping:
    validate_mode:
      type: string
      label: 'Validate mode'
    message:
      type: string
      label: 'Message'

field_validation.rule.range_constraint_rule:
  type: mapping
  label: 'Range constraint validation rule'
  mapping:
    validate_mode:
      type: string
      label: 'Validate mode'
    min:
      type: string
      label: 'Min'
    max:
      type: string
      label: 'Max'
    maxMessage:
      type: string
      label: 'Max message'
    minMessage:
      type: string
      label: 'Min message'
    invalidMessage:
      type: string
      label: 'Invalid message'
    notInRangeMessage:
      type: string
      label: 'Not in range message'

field_validation.rule.count_constraint_rule:
  type: mapping
  label: 'Count constraint validation rule'
  mapping:
    validate_mode:
      type: string
      label: 'Validate mode'
    min:
      type: string
      label: 'Min'
    max:
      type: string
      label: 'Max'
    maxMessage:
      type: string
      label: 'Max message'
    minMessage:
      type: string
      label: 'Min message'
    exactMessage:
      type: string
      label: 'Exact message'

field_validation.rule.blank_constraint_rule:
  type: mapping
  label: 'Blank constraint validation rule'
  mapping:
    validate_mode:
      type: string
      label: 'Validate mode'
    message:
      type: string
      label: 'Message'